// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfcCicXNVn1jssdlGBbhbhcRwlN9pJ7gI',
    appId: '1:65889322306:web:b9f7a7515d82a51de5b4db',
    messagingSenderId: '65889322306',
    projectId: 'trampoja-ff176',
    authDomain: 'trampoja-ff176.firebaseapp.com',
    storageBucket: 'trampoja-ff176.firebasestorage.app',
    measurementId: 'G-3JW4L46QSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfOdibv5xLcfr0L5Rgb34uH9KinkIITwE',
    appId: '1:65889322306:android:cc29b2bf86ff3c2fe5b4db',
    messagingSenderId: '65889322306',
    projectId: 'trampoja-ff176',
    storageBucket: 'trampoja-ff176.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQl3Z-XDA8NzV_3LMsg6lChQkUb7p5KlU',
    appId: '1:65889322306:ios:4b983de745ba609be5b4db',
    messagingSenderId: '65889322306',
    projectId: 'trampoja-ff176',
    storageBucket: 'trampoja-ff176.firebasestorage.app',
    iosBundleId: 'com.example.trampojaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQl3Z-XDA8NzV_3LMsg6lChQkUb7p5KlU',
    appId: '1:65889322306:ios:4b983de745ba609be5b4db',
    messagingSenderId: '65889322306',
    projectId: 'trampoja-ff176',
    storageBucket: 'trampoja-ff176.firebasestorage.app',
    iosBundleId: 'com.example.trampojaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfcCicXNVn1jssdlGBbhbhcRwlN9pJ7gI',
    appId: '1:65889322306:web:06c89cda9faf3313e5b4db',
    messagingSenderId: '65889322306',
    projectId: 'trampoja-ff176',
    authDomain: 'trampoja-ff176.firebaseapp.com',
    storageBucket: 'trampoja-ff176.firebasestorage.app',
    measurementId: 'G-ER6KQ65MGT',
  );
}
